-- UI/Shapes.lua
-- Icon shapes, shared by the Cooldown Manager proxies and the reminder buttons.
--
-- One white-on-transparent image per shape, generated by
-- .claude/make-shapes.ps1. The CDM uses each one three ways:
--   * the icon's mask (and the background's), so the icon is cut to shape
--   * the cooldown's swipe texture, so the dark sweep is the same shape. A
--     Cooldown cannot take a mask, but its swipe is drawn through this
--     texture's alpha and tinted by the swipe colour
--   * the border: the same shape drawn behind the icon, larger by the border
--     thickness and tinted the border colour, so what shows is a rim. That is
--     one image rather than a separate outline per shape, and it keeps the
--     thickness slider continuous instead of baking a width into the art
-- The reminder buttons have no sweep or border, so they only take the mask.
--
-- Each shape also has glow art (GLOW, for ns.Glow.SetShape): two flipbook
-- sheets that replace Blizzard's proc-glow art, and a static halo for the
-- self-drawn fallback.
--
-- Before 1.76 Round used Blizzard's portrait mask on the icon alone, so the
-- sweep and the border stayed square around a circle. It uses our own circle
-- now, which is what lets all three match.
--
-- An unknown saved value (a profile from a newer version, a hand edit) has no
-- entry in FILE and simply draws square.

local addonName, ns = ...

local Shapes = {}
ns.Shapes = Shapes

local SHAPE_DIR = "Interface\\AddOns\\" .. addonName .. "\\Media\\Shapes\\"

-- Display order for the dropdowns. A new shape is one line here plus its
-- images from the generator.
Shapes.LIST = {
    { value = "none",    text = "Square" },
    { value = "round",   text = "Round",   file = "circle"  },
    { value = "diamond", text = "Diamond", file = "diamond" },
    { value = "hexagon", text = "Hexagon", file = "hexagon" },
    { value = "shield",  text = "Shield",  file = "shield"  },
    { value = "heart",   text = "Heart",   file = "heart"   },
    { value = "star",    text = "Star",    file = "star"    },
}

-- One table per shape, built once here, because Glow.SetShape compares its art
-- by identity.
Shapes.FILE = {}
Shapes.GLOW = {}
for _, s in ipairs(Shapes.LIST) do
    if s.file then
        local base = SHAPE_DIR .. s.file
        Shapes.FILE[s.value] = base .. ".png"
        Shapes.GLOW[s.value] = {
            start = base .. "_proc_start.png",
            loop  = base .. "_proc_loop.png",
            halo  = base .. "_glow.png",
        }
    end
end

--- Dropdown items for a shape picker.
function Shapes.DropdownItems()
    local items = {}
    for _, s in ipairs(Shapes.LIST) do
        items[#items + 1] = { text = s.text, value = s.value }
    end
    return items
end

--- Cut `...` (textures, the first of which the mask is sized to) to `shape`,
--- or put them back square. The mask lives on `owner` and is reused, so pass
--- the same textures every time for the same owner. Returns the shape's image
--- path, or nil for square.
---
--- Always off before on. RemoveMaskTexture rather than just hiding it: a
--- hidden mask still clips on some builds, which showed up as icons staying
--- round after the option was switched back off. Removing first also means
--- moving from one shape to another never leaves the mask added twice.
---@param shape string?
function Shapes.SetMask(owner, shape, ...)
    local file = shape and Shapes.FILE[shape]
    local n = select("#", ...)

    local m = owner._sqMask
    if m and owner._sqMaskOn then
        for i = 1, n do
            local tex = select(i, ...)
            if tex then tex:RemoveMaskTexture(m) end
        end
        m:Hide()
        owner._sqMaskOn = false
    end

    if not file then return nil end

    if not m then
        m = owner:CreateMaskTexture()
        m:SetAllPoints((...))
        owner._sqMask = m
    end
    m:SetTexture(file, "CLAMPTOBLACKADDITIVE", "CLAMPTOBLACKADDITIVE")
    m:Show()
    for i = 1, n do
        local tex = select(i, ...)
        if tex then tex:AddMaskTexture(m) end
    end
    owner._sqMaskOn = true
    return file
end
